### PR TITLE
DM-19575: Add Storable mixin to ExposureInfo components

### PR DESCRIPTION
**Pull request by kfindeisen**
This PR adds the `Storable` mixin to all `afw` classes in `ExposureInfo` (note that it does not modify `daf::base::PropertySet`, which as noted on [Jira](https://jira.lsstcorp.org/browse/DM-19575) will need special treatment for now). This amounts to adding the following four methods, though some keep their default implementation of throwing an `UnsupportedOperationException`:
* `cloneStorable`: creates a `shared_ptr<Storable>`; implemented in terms of a more specific `clone` if applicable. Using a virtual `cloneStorable` instead of shadowing (as was done with e.g. `BaseTable`) is less prone to developer error, because only one implementation is required (e.g., in `Psf`) rather than one for every subclass.
* `equals`: compares the object to any `Storable`, usually returning `false` for mixed-class comparisons. Implemented in terms of `operator==` if applicable and appropriate.
* `toString`: returns a string representation of an object. I found it easier to reimplement `operator<<` in terms of `toString` rather than vice versa (the latter would have involved a method template in `Storable.h` that would introduce extra dependencies).
* `hash_value`: conforms to the convention I introduced in #410, so no delegation required.

A couple of design issues for which I would like feedback:
* I'm really unhappy about making `cloneStorable` return `shared_ptr` rather than `unique_ptr` (which is more flexible for the client; see Effective Modern C++), especially since doing so imposes awkward implementation constraints on `PolymorphicValue`. However, it's not possible to implement a `unique_ptr` clone in terms of a `shared_ptr` clone if you don't already have a `unique_ptr` clone, and trying instead to change `Psf::clone` to use `unique_ptr` triggers a [pybind11 bug](https://github.com/pybind/pybind11/issues/1138) that, judging from the discussion in related PRs, will never be fixed. A third option would be appreciated.
* the `singleClassEquals` helper is a static method template so that subclasses of `Storable` can cast to the correct type, and to duck-type around the fact that `Storable` itself does not implement `operator==`. The code works and is clean, but I feel like there should be a more natural solution.
* `Storable` imposes a lot of API clutter on its subclasses, especially since the "unsupported" versions of methods still appear in the documentation. Currently `cloneStorable` is absolutely essential, and `equals` is needed for C++ equality comparisons of `GenericMap`. We do not use `toString` (no `GenericMap` printing yet) or `hash_value`. Can we afford to remove these methods? If we do, they will be hard to add later, scaling to the number of subclasses `Storable` has.
* Adding `Storable` to `Filter` required implementing `Persistable` in `Filter`. I cargo-culted the code from `ApCorrMap`, so a careful review would be appreciated.

### CODE REVIEW

**Comment by kfindeisen** [comment]
Update on the API clutter question: perhaps it's best to support the methods, and find some automated way to hide the unimplemented ones. While working on `GenericMap` iteration I realized that it's a lot of work (casting) to perform operations that aren't supported by `Storable`. On the other hand, needing to handle `UnsupportedOperationException` is also a lot of work...

File: include/lsst/afw/typehandling/Storable.h [hunk 1]
```diff
@@ -101,8 +101,46 @@ class Storable : public table::io::Persistable {
...
+     * @note This method template calls `operator==` with arguments of type
+     *       `T const&`. Its use is *not* recommended if there would be any
+     *       ambiguity regarding which `operator==` gets called.
+     *
+     * This method template is typically called from @ref equals as:
+     *
+     *     bool MyType::equals(Storable const& other) const noexcept {
+     *         return singleClassEquals(this, other);
+     *     }
+     */
```
Comment (TallJimbo) [inline include/lsst/afw/typehandling/Storable.h]: This might be a context where providing a preprocessor macro would be useful, or perhaps a CRTP implementation mixin - something like:
```
template <typename Derived>
class EqualityComparableStorable : public Storable {
public:
    bool equals(Storable const & other) const noexcept override {
        Derived const & lhs = static_cast<Derived const &>(*this);
        ... singleClassEquals logic here...
    }
};
```
But of course macros have their own problems, and generalizing that CRTP idea to support more `Storable` methods is *at least* quite complicated (maybe one CRTP mixin, with bool template parameters to indicate which `Storable` operations to implement via various standard operators, and lots of partial specialization?).

Anyhow, what you have here is just fine and quite possibly better than either of those ideas; I'm just suggesting other options because you asked for them :smiley:.

File: python/lsst/afw/typehandling/_Storable.cc [hunk 2]
```diff
@@ -46,8 +46,9 @@ void wrapStorable(utils::python::WrapperCollection& wrappers) {
     wrappers.wrapType(PyStorable(wrappers.module, "Storable"), [](auto& mod, auto& cls) {
         // Do not wrap methods inherited from Persistable
         cls.def(py::init<>());  // Dummy constructor for pure-Python subclasses
-        cls.def("__copy__", &Storable::clone);
-        cls.def("__deepcopy__", [](Storable const& self, py::dict const& memo) { return self.clone(); },
+        cls.def("__copy__", &Storable::cloneStorable);
+        cls.def("__deepcopy__",
+                [](Storable const& self, py::dict const& memo) { return self.cloneStorable(); },
```
[the remark this answers is not in the document]
Comment (kfindeisen) [reply python/lsst/afw/typehandling/_Storable.cc]: Hmm, I guess I didn't explicitly specify that. To me, "copy" implies "deep copy". :confused: Though I do require that `cloneStorable` have the same behavior as `clone` if the latter exists, and I suppose there could be a shallow-copy `clone` in the Stack.

I consider `bool deep` an anti-pattern, given that:
* there's pretty much no reason to want a shallow copy if the class is mutable (or rather, you can't think of the result as a "copy"), whereas there's no reason to want a deep copy if the class is immutable
* a method that performs both shallow and deep copies, notwithstanding the above, is doing two different operations, violating the single responsibility principle
* default parameters are easy to overlook when learning an API by looking at the code; if the parameters control fundamental changes in what a function/method does, those changes may be hidden

I suppose we could remove these pybind11 bindings, since I don't think they're needed to use Python subclasses of `Storable` from C++ (though I'd rather wait until [DM-19582](https://jira.lsstcorp.org/browse/DM-19582) before swearing to that).

File: src/typehandling/PolymorphicValue.cc [hunk 3]
```diff
@@ -30,19 +30,19 @@ namespace lsst {
 namespace afw {
 namespace typehandling {
 
-PolymorphicValue::PolymorphicValue(Storable const& value) : _value(value.clone()) {}
+PolymorphicValue::PolymorphicValue(Storable const& value) : _value(value.cloneStorable()) {}
```
[the remark this answers is not in the document]
Comment (kfindeisen) [reply src/typehandling/PolymorphicValue.cc]: I think that would work (assuming that `moveIntoPointer` is a method on `Storable`, analogous to `cloneStorable`), the main issue is API clutter.

File: include/lsst/afw/typehandling/PolymorphicValue.h [hunk 4]
```diff
@@ -137,7 +137,8 @@ class PolymorphicValue final {
     std::size_t hash_value() const;
 
 private:
-    std::unique_ptr<Storable> _value;
+    // unique_ptr would be more appropriate, but Storable::cloneStorable must return shared_ptr
+    std::shared_ptr<Storable> _value;
```
[the remark this answers is not in the document]
Comment (kfindeisen) [reply include/lsst/afw/typehandling/PolymorphicValue.h]: I don't understand your first point. How does making a factory method return `shared_ptr` "allow" `make_shared`? Can't you call `make_shared` for any class that has a public constructor?

Re: points 2 and 3, I don't think `Psf` is the problem. It's simply the first time we've tried to retrofit `Storable` onto an existing class hierarchy. I already rejected the manual lambda idea on the grounds that it would make it hard to use `Storable` correctly -- anybody trying to make another cloneable class storable would need to know to repeat the trick.

I don't think the fourth point is relevant because we don't want to transfer ownership from Python (a C++ function that takes `unique_ptr` input would have unintuitive side effects anyway). Having a `unique_ptr` return value corresponds to transferring ownership *to* Python, which we do often.

File: include/lsst/afw/typehandling/Storable.h [hunk 5]
```diff
@@ -101,8 +101,46 @@ class Storable : public table::io::Persistable {
...
+    /**
+     * Test if a Storable is of a particular class and equal to another object.
+     *
+     * This method template simplifies implementations of @ref equals that
+     * delegate to `operator==` without supporting cross-class comparisons.
+     *
+     * @tparam T The class expected of the two objects to be compared.
+     * @param lhs, rhs The objects to compare. `lhs` is passed by pointer
+     *                 because it should almost always be `this` (see
+     *                 example below).
```
[the remark this answers is not in the document]
Comment (kfindeisen) [reply include/lsst/afw/typehandling/Storable.h]: My main motivation was hearing Python programmers complain about how our C++ codebase requires a lot of gratuitous `*`/`&` to deal with our mixing of pointers and references. Easy enough to change, though.

File: src/image/Filter.cc [hunk 6]
```diff
@@ -168,6 +173,64 @@ std::vector<std::string> Filter::getNames() {
...
+
+class FilterFactory : public table::io::PersistableFactory {
+public:
+    std::shared_ptr<table::io::Persistable> read(InputArchive const& archive,
+                                                 CatalogVector const& catalogs) const override {
+        PersistenceHelper const& keys = PersistenceHelper::get();
+        LSST_ARCHIVE_ASSERT(catalogs.size() == 1u);
+        LSST_ARCHIVE_ASSERT(catalogs.front().getSchema() == keys.schema);
+        return std::make_shared<Filter>(catalogs.front().begin()->get(keys.name));
+    }
```
[the remark this answers is not in the document]
Comment (kfindeisen) [reply src/image/Filter.cc]: Hmm, must have misunderstood how the registry was populated.

Do you recommend removing `Storable` entirely, or keeping the other `Storable` capabilities and making `isPersistable` return `false`?

**Comment by kfindeisen** [comment]
> On that subject, I think reducing Python API clutter is probably more important than C++ API clutter - because Python APIs are actually introspectable via things like tab-completion (though perhaps that attitude really just reflects my lack of C++ editor/IDE sophistication).

I wasn't thinking in terms of tab completion at all; I was motivated by looking at the Doxygen docs for the `Storable` classes.

> We could consider either not wrapping the `Storable` base API for Python (relying on derived classes that implement those methods to do so where appropriate)

I'm a little worried that this would interfere with adding pure-Python subclasses of `Storable`, but it might be best to do that now and revert if [DM-19582](https://jira.lsstcorp.org/browse/DM-19582) proves it necessary.

> We could also do something similar in C++ if you think the API clutter there is a big problem, by making the entire `Storable` API protected virtual with friend-function public access.

I don't think doing that would reduce API clutter at all -- the number of methods/functions a user would need to be aware of, including semi-overloads like `clone` vs. `cloneStorable`, would be the same.

**Comment by kfindeisen** [comment]
I've gone ahead and removed the pybind11 wrappers for the optional `Storable` methods, as well as for `UnsupportedOperationException`.

File: src/image/Filter.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (kfindeisen) [reply src/image/Filter.cc]: On second thought, are you sure there's a problem with `Filter` depersistence? It looks like the existing code simply [calls the constructor with force=true](https://github.com/lsst/afw/blob/master/src/image/ExposureFitsReader.cc#L85).

File: include/lsst/afw/typehandling/PolymorphicValue.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (TallJimbo) [reply include/lsst/afw/typehandling/PolymorphicValue.h]: On point (1), I just mean that if you define `clone` to return `unique_ptr`, but always in practice convert that `unique_ptr` into a `shared_ptr`, you've missed out on the optimization that `make_shared` provides, while if you define `clone` to return `shared_ptr`, you can implement it via `make_shared`.

File: src/image/Filter.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (TallJimbo) [reply src/image/Filter.cc]: I think you're right - for some reason I had it in my head that it was `force=false` right now, and moreover that it couldn't easily be changed.  No idea what my past self was thinking.

I think that means we should keep this implementation, but when we get to reimplementing `Exposure`, we should pause and think about whether to use the new `Filter` persistence there, just because that's another on-disk format change we'll have to support going forward.  I don't think that's a problem if we continue to special-case `Filter` by also writing the name into the header.

**Comment by TallJimbo** [comment]
> I don't think doing that would reduce API clutter at all -- the number of methods/functions a user would need to be aware of, including almost-overloads like clone vs. cloneStorable, would be the same.
I think the relevant question is *which* user(s); to me, at least, regular methods say, "this is an integral part of this class", which means the clutter affects all users of the class.  Depending on how and where you put them, friends can be used to say "this is a specialized corner of the API targeted at a specific audience".  Depending on how much `Storable` is there really just for `GenericMap` (and I don't think we've really decided strongly either way what our philosophy is on that), that may be more appropriate.

**Comment by TallJimbo** [comment]
Sorry for the delay in responding.  If I've failed to comment on something blocking you, please do ping me again.

File: src/image/Filter.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (kfindeisen) [reply src/image/Filter.cc]: Honestly, I'm not sure any generic persistence framework will be backwards-compatible with the existing file format, even for "normal" components. For DM-17982 I'm considering leaving the persistence code as-is, and supporting unknown `Storable`s later.
